### ISSUE TITLE
Socket.Io running HTTPS behind AWS ELB

### ISSUE THREAD

**Issue by ngzhongcai** [findhit/proxywrap#10]
Hi, 

I am trying to deploy for Socket.io running HTTPS behind AWS ELB.
This is how I implemented.

``` javascript
var https= require("https");
var proxiedHttp= require("findhit-proxywrap").proxy(https, { strict: false, overrideRemote: true });
var server= proxiedHttp.createServer(options);
server.listen(3000, function() { console.log("SERVER STARTED"); });
var io= require("socket.io").listen(server);
```

At https://github.com/findhit/proxywrap/blob/master/lib/proxywrap.js#L134, I added a console.log(header), and it appears that header was a string of gibberish nonsense. As though it's still in unencrypted HTTPS.

Like to ask if I have deployed your script wrongly?
Appreciate any advise!

**Comment by cusspvz** [comment]
Hi @ngzhongcai 

> I am trying to deploy for Socket.io running HTTPS behind AWS ELB.

Was discovered by @AbdelMat-CP on issue #9 that are some implementation problems with **https** when running on top of node *0.12.2*.

To isolate that problem we must first complete **https** tests support, if you could help us, it would be awesome!

Currently my timespan for side projects is very narrow, so i could not complete it on the next days.

ATM, we are also using https with *AWS ELB*, but for performance proposes, we let the **https** handling on *AWS ELB* endpoint.
If you want to workaround this problem, you could configure *AWS ELB* like **80 http -> 3000 http, 443 https -> 3000 http** and keep *http* on instance nodes.

**Comment by cusspvz** [comment]
Gonna let this issue opened so we can track in case this incident is different.

**Comment by ngzhongcai** [comment]
Am running on 10.36.
Can I say that I have deployed the script correctly.

**Comment by cusspvz** [comment]
Just remembered that *AWS ELB* has a problem with Socket.IO, have you configured *AWS ELB* with *http* or *tcp*?

**Comment by ngzhongcai** [comment]
Thanks for the tip! I will try terminating at elb later

**Comment by ngzhongcai** [comment]
Doing it as TCP

**Comment by cusspvz** [comment]
Please try *ELB* as `stcp -> tcp` and use `require( 'http' )` on your app instead.

**Comment by cusspvz** [comment]
You could want to redirect entire requests from http to https, for that you should detect which port is being accessed on *ELB* (through `socket.proxyPort`) and redirect in case it isn't `443`.

**Comment by cusspvz** [comment]
Solved?

**Comment by ngzhongcai** [comment]
Nope. Not exactly. Sorry that I closed the issue unilaterally.

I made a few changes to my setup.
1. Like what you suggested, I let it terminate at the load balancer to get more performance
2. Instead of using Socket.io, I am now using WS Websocket only. https://github.com/websockets/ws

Tried to deploy WS server on top of ProxyWrap, but was unable to get it working. Turns out that you will need to suppress any remnants of ProxyProtocol strings before passing it through. Otherwise the WS server will not work.

Instead of amending on ProxyWrap, I amended the HTTP handler of WS server instead.

**Comment by cusspvz** [comment]
Tried to deploy WS server on top of ProxyWrap, but was unable to get it working. Turns out that you will need to suppress any remnants of ProxyProtocol strings before passing it through.

Strange, could you did something wrong? We use *findhit-proxywrap* on our production servers with *Socket.IO* and SSL support (trough ELB) without any problems.

I will remain this issue opened until we have our test suite ready for `https` protocol.

Thanks for reporting! :)

**Comment by ngzhongcai** [comment]
Strange... I deployed WS similar to the first chunk of codes earlier.
And like yourself, I terminated SSL at ELB.

**Comment by asgoel** [comment]
@ngzhongcai am trying to get a similar setup with WS websocket behind ELB working. How did you end up modifying the WS server in order to get it to work?

**Comment by cusspvz** [comment]
Should work with `v0.3.12`
