### ISSUE TITLE
TCP port are from 1 to 65535 and not from 1 to 65335

### ISSUE THREAD

**Issue by mvalo** [findhit/proxywrap#13]
Hi,
In your regexp, you test if the port is contained in [1..65335].
But TCP ports are going until 65535.

Issue in on file "proxy-protocol.regexp.js".

Before : 
Port = '([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-2][0-9]{2}|653[0-2][0-9]|6533[0-5])'; // 1..65335

After correction of your regexp :
Port = '([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-3][0-9]|6553[0-5])'; // 1..65535

**Comment by cusspvz** [comment]
@mvalo 0.3.10 release already contains your contributions! Thanks once again! :)

**Comment by mcullmann** [comment]
Hi,

I find accidentally this entry and realized there is a little mistake in the pattern:

"After correction of your regexp :
Port = '([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-3][0-9]|6553[0-5])'; // 1..65535"

This Pattern is allowed for the range between 1-65539, it should be:
Port = '([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])'; // 1..65535

**Comment by cusspvz** [comment]
@mcullmann thanks for your comment!

I believe thats the Pattern we have at the latest version:
https://github.com/findhit/proxywrap/blob/master/lib/proxy-protocol.regexp.js#L85
