### ISSUE TITLE
Unable to mix proxied and unproxied services?

### ISSUE THREAD

**Issue by fidian** [findhit/proxywrap#22]
After the library patches `http`, is it possible to have an API that is not served with proxy protocol?

Amazon's ELBs can be configured to forward TCP traffic, which works wonderfully but one loses the source IP.  The ELB can be modified to use Proxy Protocol to forward on the original connection's information.  You knew that, obviously.  The ELB can be configured with a health check.  I am unable to configure an HTTP health check because the ELB sends requests (missing the Proxy Protocol header) to the HTTP health check endpoint.  I must resort to TCP health checks, which means the port should be open when life is good and I should close it if I don't want traffic at this moment.

Is there a way to not patch `http` and have a new object get created that retains the properties from `http` and has a patched `Server`?

**Comment by fidian** [comment]
Nevermind, I have completely misunderstood how this works.  :-)

**Comment by cusspvz** [comment]
There is the `strict` option that lets you define the behavior to take whenever there is an incoming connection without the PP headers, if it should let it bypass or threat it as an error.

Aorry for my late response. :)
