### ISSUE TITLE
Can't detect Socket.io 'disconnet' event when using via Amazon ELB

### ISSUE THREAD

**Issue by moshest** [findhit/proxywrap#24]
It's looks like I'm getting `disconnect` only when Socket.io tries to send something to the disconnected client later on.

Does anyone was that issue also? [See more info here..](http://stackoverflow.com/questions/36575692/cant-detect-socket-disconnect-on-socket-io-via-ec2-load-balancer-elb)

**Comment by cusspvz** [comment]
Are you using websocket ou long polling transports? On those cases, which are active? Does it happens with both transport layers?

**Comment by moshest** [comment]
Web socket. Long polling transport works bad on ELB because it's jumbs between instances all the time.

**Comment by cusspvz** [comment]
Have you check if this isn't a session issue?

**Comment by cusspvz** [comment]
Closed because OP hasn't respond. Please ask for re-open if it is still an issue.
